_doc_: "Configuration parameters for the driver behavior"

# Behavior:
driver_revolution_signal_blind_time:
  value: 2
  c_type: int
  comment: "Time in millis where interrupts are ignored because the signal might be fuzzy and result in multiple signal edges."
driver_braking_threshold_rpm:
  value: 80
  c_type: int
  comment: "Threshold as difference between current and target speed (in RPM) at which the brakes will be engaged to further decelerate."