name: Canary Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # manual trigger

permissions:
  contents: read

jobs:
  build-connector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: Install dependencies
        working-directory: ./connector
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build
      - name: Package
        working-directory: ./connector
        run: |
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: connector-canary-release
          path: dist/
  release:
    runs-on: ubuntu-latest
    needs:
      - build-connector
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: connector-canary-release
          path: dist/
      - name: Deploy canary release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'canary'
          prerelease: true
          title: "Canary Release"
          files: |
            dist/*
